- hosts: all
  tasks:

    - name: Install binary dependencies from diskimage-builder
      include_role:
        name: bindep
      vars:
        bindep_dir: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/diskimage-builder'].src_dir }}"

    - name: Install requirements for ironic-python-agent-builder
      pip:
        requirements: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/ironic-python-agent-builder'].src_dir }}/requirements.txt"
        extra_args: -c "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/requirements'].src_dir }}/upper-constraints.txt"
      become: true

    - name: Install ironic-python-agent-builder
      pip:
        name: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/ironic-python-agent-builder'].src_dir }}"
        editable: true
      become: true
